# Site settings
title: Nicolas POTIER
description: Page personelle de Nicolas Potier
keywords: Nicolas Potier, ACSEO
author: Nicolas POTIER
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nicolaspotier.fr" # the base hostname & protocol for your site
